### ISSUE TITLE
Online Virus check failed 

### ISSUE THREAD

**Issue by dgil59** [winsiderss/systeminformer#2382]
First, let me tell you how much i love this tool.
I'm trying last version downloaded today : SI 3.2.25011.2103 (bfbd548b) release. 

I take a  process randomly to check potential virus online (menu option "_Send to_" from process contextual menu). 
Only virusscan.jotti works whereas both other checks fail.!
Even when using menu Tools/Online Checks/Update file to virustotal.

![Virus check failed](https://github.com/user-attachments/assets/ec667373-6112-4218-9432-bb2a35141783)

NB : when checking manually the same file myself going on the _virustotal.com_ website ; all is good.

**Comment by dmex** [comment]
Fixed in latest canary build. You'll need to add your apikey to the Options window > OnlineChecks settings:

https://docs.virustotal.com/docs/please-give-me-an-api-key

![Image](https://github.com/user-attachments/assets/c9935149-af25-4e32-850b-853ae7d5b60f)

**Comment by dgil59** [comment]
I did not know it...
Thank you for this precision.

**Comment by enervated** [comment]
> Fixed in latest canary build. You'll need to add your apikey to the Options window > OnlineChecks settings:
> 
> https://docs.virustotal.com/docs/please-give-me-an-api-key
> 
> ![Image](https://github.com/user-attachments/assets/c9935149-af25-4e32-850b-853ae7d5b60f)

Was anyone able to get this working? I'm running 3.2.25056.2303 canary and have entered my API key, but the VirusTotal column still displays "Scanning disabled".

**Comment by enervated** [comment]
Yeah, as stated, I'm running 3.2.25056.2303 canary and have my own API key from VirusTotal. Still not working.

ProcessHacker.OnlineChecks.EnableVirusTotalScanning is set to 1 as well.

**Comment by dgil59** [comment]
I just done a recheck of that feature  with the last canary build available online and it works !

![Image](https://github.com/user-attachments/assets/9ec55db4-fbd1-4e33-8e8b-1d0709bcfdff)
![Image](https://github.com/user-attachments/assets/fb8529d8-59b1-42b4-9aaf-106d19594a97)
![Image](https://github.com/user-attachments/assets/c858a394-d8aa-449c-a909-a70caebaf476)
![Image](https://github.com/user-attachments/assets/1092a2ae-5119-4122-8fb9-a35433774b75)
![Image](https://github.com/user-attachments/assets/2fbdd2db-ac4b-400b-b7ed-fdb0786a35e6)

**Comment by enervated** [comment]
No one is mentioning the VirusTotal column. All my VT features work except that the VirusTotal column still displays "Scanning disabled". Why would that be?

![Image](https://github.com/user-attachments/assets/ff83338d-9dd9-4a83-a4c5-7d8b12dc7cfd)
