### ISSUE TITLE
"Hide default services" doesn't work anymore

### ISSUE THREAD

**Issue by sergwish** [winsiderss/systeminformer#2510]
### Brief description of your issue

I'm unable to filter out services created by Microsoft from the total list of services in the Services tab. 
Current stable version does not have this bug.

### Steps to reproduce (optional)

1. Switch to "Services" tab of the main window of System Informer.
2. In the main menu open "View" submenu and tick/untick "Hide default services".

### Expected behavior (optional)

When "Hide default services" is ticked list of services must shorten significantly, hiding services by Microsoft.

### Actual behavior (optional)

The list of services is unchanged, services by Microsoft are present regardless.

### Environment (optional)

```shell

```

**Comment by dmex** [comment]
This feature has two modes. If you've enabled service signature checking then it'll check the signature for specific OS Component bits and is the most reliable since not all services from Microsoft are default - this feature was working but the legacy fallback method of checking version information stopped working - there was a regression from additional checking of version info since anyone can change that information and is fixed in the latest update - enabling service signatures is recommended.

**Comment by sergwish** [comment]
Great! Except in current canary it still doesn't work.
Screenshot added.

![Image](https://github.com/user-attachments/assets/6c963b31-fcc9-4287-9c8f-cfe77b705ac4)

**Comment by dmex** [comment]
@sergwish Was it fixed in recent canary builds?
