### ISSUE TITLE
[Suggestion] Implement sensors information (CPU/GPU...) along side PH graphs

### ISSUE THREAD

**Issue by XCanG** [winsiderss/systeminformer#664]
In Process Hacker graphs (View -> System Information) I always missed sensor information from CPU, GPU, etc. I run GPU-Z if I want to get graphs, but it's not convenient to have separate programs to look at this stuff, so the idea is include this in PH system info window. This may be implemented and enabled optionally from the settings. May be as well add ability to show it in tray.

I'm not looking at very detailed info, but what is important is CPU, GPU temperature, GPU and Memory clock and I wish it to see as graphs (this is also why I choose to use GPU-Z as other programs show only current state).

I'm working with image processing, specifically using Tensorflow, so this info would be convenient if it would in one place.

**Comment by Syst3mSh0ck** [comment]
I think you're looking for the Performance Counters which are available using PerfMonPlugin found at https://github.com/processhacker/plugins-extra

**Comment by XCanG** [comment]
Oh, interesting, didn't know about that, but is there are compiled dll's instead source code? @Syst3mSh0ck

**Comment by Biswa96** [comment]
plugins-extra can be added in CI builds. What do you think @dmex?

**Comment by Msprg** [comment]
Hello, the project has been renamed since, but what's the current status of this issue? The linked plugins weren't updated for a long time, is there a current way to get at least the CPU temp graph?

I'm still very much interested in this feature

**Comment by XCanG** [comment]
> Hello, the project has been renamed since, but what's the current status of this issue? The linked plugins weren't updated for a long time, is there a current way to get at least the CPU temp graph?
> 
> I'm still very much interested in this feature

Hm, that's interesting, I didn't know about rename and just download SystemInformer nightly build about 30 mins ago and actually I was surprised by amount of new features it provide on top of existing ones. And having dark theme is top notch as well!

Regarding this issue I think it is resolved now and could be closed, because there is implemented all graphs I would need.

Example of new graphs from quick test:
![image](https://github.com/winsiderss/systeminformer/assets/4011523/bfd1cef8-4d6b-496f-8cd6-21537696b3dd)

**Comment by Msprg** [comment]
> Regarding this issue I think it is resolved now and could be closed, because there is implemented all graphs I would need.


I'm glad it's solved for your use case, however I'd still like to have a CPU (not just GPU) temperature, and it's still not "everything". Of the top of my head, frequency monitoring would also be useful for example...


Not to mention options to disable individual graphs, for example laptop GPUs don't always provide all the information, at least mine doesn't so graphs such as fan speed and power consumption are useless and just take up space unnecessarily since they never have any data.


I see the issue is back open already which I feel is appropriate, and I also take it it's not implemented yet.

**Comment by MonsterSe7en** [comment]
Would love to have a CPU Temperature monitor in my System Tray like there's one for GPU Temp

Please check the 2nd Icon (GPU Temp)
![image](https://github.com/user-attachments/assets/ed465a78-13f4-48cd-9471-3bbb31f5ec78)

Would love a *CPU Temp (Text)* option as well like *GPU Temp (Text)*
Please refer last option under Tray Icons in Screenshot!
![image](https://github.com/user-attachments/assets/7d0eb3eb-2b79-4cfb-b0bf-3022c694470d)
