### ISSUE TITLE
Mini-"top" display missing from Windows 11 tray icon

### ISSUE THREAD

**Issue by robertroessler** [winsiderss/systeminformer#941]
Since installing the first BETA of Win 11 Pro "21H2" build 22000.100, instead of the usual "top 5 CPU users" (or whatever the official definition is), I only see a global CPU usage value and the [presumed] single top CPU user, both in a small-ish "tip"-style box.

This is observed on PH 3.0.4234.

It has been suggested that Win 11 is now interfering with tray icon messages(?).

No other weirdnesses observed, and the rounded corners being forced on the app look fine.

**Comment by dmex** [comment]
> It has been suggested that Win 11 is now interfering with tray icon messages

Microsoft started blocking NIN_POPUPOPEN messages that Process Hacker needs for showing the tray information window.

No warnings or errata has been published about deprecation of these messages so it's likely these notification messages were deliberately disabled to give Microsoft Task Manager and Microsoft Process Explorer yet another competitive advantage because they we're unable to implement their own rich tray information like what Process Hacker was providing users.

**Comment by dmex** [comment]
> It has been suggested that Win 11 is now interfering with tray icon messages

Yes. Windows 11 blocked these messages by default but the latest build has restored some functionality.

You need to single-click the icon once then Win11 will display the mini-info panel. Previous versions of Windows would display the panel on mouseover but Windows 11 will only show the panel after clicking once.

You can also now click+drag the icons out of the overflow menu onto the taskbar.

**Comment by AzAgarampur** [comment]
WM_POPUPOPEN is generated ~500ms after single clicking the tray icon on Windows 11 RTM

**Comment by dmex** [comment]
Recent Win11 updates re-introduced the notifications. You have to click the tray icon just once and the window becomes visible 👍

**Comment by robertroessler** [comment]
Umm... not sure if clear communication is taking place - as soon as I saw this, I did a git pull and rebuild.

Even after a couple restarts, and using the "Enable tray information window" and "Single-click tray icons" options, I am _not_ seeing the "mini-Top" (your "tray information window") display activating on hover.

My Win 11 "Insiders" build is BETA 22623.1037, the System Informer build is... well, your About doesn't really reflect much (anything) for a local build from latest git sources.  The popup I see if I ask to check for newer builds always says 3.0.5578, the Changelog from that popup shows "Remove legacy PhGetGlobalTimerQueue" as the most recent commit.

Did I not get the latest change, is my Windows version not new enough (maybe the notification thing is only fixed in the "Dev" builds?), or am I misunderstanding what I am supposed to be seeing: hover over the SI tray icon gives the full info window, while single-click activate the app window?

**Comment by ForNeVeR** [comment]
> Even after a couple restarts, and using the "Enable tray information window" and "Single-click tray icons" options

Try disabling the **Single-click tray icons**. This is still broken in Windows I think: it never delivers the mouse hover message over the tray icons, and only delivers the clicks.

So, if you click the icon and have **Single-click tray icons** enabled, then the Process Hacker (or should I say SystemInformer already?) window gets focused.

If you click the icon and have **Single-click tray icons** disabled, then the normal code triggering the popup gets triggered and shows the popup.

It is surely a step back from the old experience for me, but still it kinda works.

I don't think that anything has been changed in recent Windows versions; it was working the same for me all the way since Windows 11 release. Sadly.

**Comment by dmex** [comment]
> "Single-click tray icons" options

This option isn't compatible with the tray information window on Windows 11 because the shell needs the single click to activate the tray window.

> I am not seeing the "mini-Top" (your "tray information window") display activating on hover.

Microsoft removed the hover functionality from the shell and replaced it with single-clicking the icon.

> Did I not get the latest change, is my Windows version not new enough (maybe the notification thing is only fixed in the "Dev" builds?), or am I misunderstanding what I am supposed to be seeing

The changelog is realtime copied from github but the nightly build hasn't been updated since the 23rd of November. There's no changes in the nightly build for either tray icons or the information window.

**Comment by robertroessler** [comment]
Yup, we really aren't communicating... ;)

If we still need to dedicate the click to opening the information window, then what did it mean to say that the notification messages are back?  That was the whole point of this issue when it was opened: _with_ notifications, we can get **everything** - info window on hover, and app window on click - and this scenario worked in Win 10, but went away with Win 11.

I do wish the Windows team would quit messing with things that worked well... we just got back the ability to order icons in the tray the way we want them (after this ability flipping out and back in and out again for many months now).  Sigh.

**Comment by dmex** [comment]
> That was the whole point of this issue when it was opened: with notifications, we can get everything - info window on hover, and app window on click - and this scenario worked in Win 10, but went away with Win 11.

Developers are supposed to be migrating these tray features into the widgets dialog:
https://user-images.githubusercontent.com/1306177/209466253-812f7c80-8f93-4ccb-8f23-b794f3846ac5.png

The context menus were also changed for the same reason to make developers package their applications to provide context menus as are a bunch of other changes.

> we just got back the ability to order icons in the tray the way we want them

Submit a feature request to either Start11, StartIsBack or Open Shell and they'll include the functionality on Win11 without having to wait for Windows 12 👍

**Comment by dmex** [comment]
> Microsoft removed the hover functionality from the shell

Microsoft added tray hover functionality and WM_POPUPOPEN notifications with update KB5022913 released yesterday 🥳

**Comment by Biswa96** [comment]
It is reported that same KB5022913 broke those 3rd party start-menu software https://www.theregister.com/2023/03/01/microsoft_windows_11_crash/

**Comment by Masamune3210** [comment]
The shell changed, it's normal for modifications to explorer to cause things that try to patch it to not work correctly until they are updated
